import { dbConnect } from "@/lib/db"
import { HOME_SEED } from "@/lib/homepage-defaults"
import { SiteConfig } from "@/lib/models/SiteConfig"
import { NavMenu } from "@/lib/models/NavMenu"
import { HomePage } from "@/lib/models/HomePage"
import { AboutPage } from "@/lib/models/AboutPage"
import { FAQ } from "@/lib/models/FAQ"
import { FooterContent } from "@/lib/models/FooterContent"
import { LegalNotice } from "@/lib/models/LegalNotice"
import type {
  SiteConfigData, NavMenuData, HomePageData, AboutPageData,
  FAQData, FooterData, LegalNoticeData, LegalNoticeType,
} from "@/types/cms"
import type { Locale } from "@/lib/i18n/config"

// ─── Defaults ────────────────────────────────────────────────────────────────

const DEFAULT_SITE_CONFIG: SiteConfigData = {
  logoUrl: "", logoPubId: "", siteName: "ჩემი იურისტი", tagline: "",
  favicon: "", contactEmail: "", contactPhone: "", contactPhoneVisible: false, contactAddress: "", socialLinks: {},
}

const DEFAULT_NAV: NavMenuData = {
  items: [
    { _id: "1", label: "მთავარი", href: "/", order: 0, isExternal: false },
    { _id: "2", label: "ჩვენ შესახებ", href: "/about", order: 1, isExternal: false },
    { _id: "3", label: "სერვისები", href: "/services", order: 2, isExternal: false },
    { _id: "4", label: "კანონმდებლობა", href: "/legislation", order: 3, isExternal: false },
    { _id: "5", label: "ფასები", href: "/pricing", order: 4, isExternal: false },
    { _id: "6", label: "კითხვები", href: "/faq", order: 5, isExternal: false },
  ],
  status: "published",
}

const DEFAULT_FOOTER: FooterData = {
  columns: [], disclaimer: 'გაფრთხილება: „პასუხი გენერირებულია ხელოვნური ინტელექტის მიერ და ეფუძნება მოქმედ კანონმდებლობას. ოფიციალური იურიდიული დასკვნისთვის მიმართეთ იურისტს."', copyright: "© 2026 ჩემი იურისტი - ყველა უფლება დაცულია.", status: "published",
}

const DEFAULT_SITE_CONFIG_EN: SiteConfigData = {
  logoUrl: "", logoPubId: "", siteName: "My Lawyer", tagline: "Law in plain language",
  favicon: "", contactEmail: "", contactPhone: "", contactPhoneVisible: false, contactAddress: "", socialLinks: {},
}

const DEFAULT_NAV_EN: NavMenuData = {
  items: [
    { _id: "1", label: "Home", href: "/", order: 0, isExternal: false },
    { _id: "2", label: "About us", href: "/about", order: 1, isExternal: false },
    { _id: "3", label: "Services", href: "/services", order: 2, isExternal: false },
    { _id: "4", label: "Legislation", href: "/legislation", order: 3, isExternal: false },
    { _id: "5", label: "Pricing", href: "/pricing", order: 4, isExternal: false },
    { _id: "6", label: "FAQ", href: "/faq", order: 5, isExternal: false },
  ],
  status: "published",
}

const DEFAULT_FOOTER_EN: FooterData = {
  columns: [], disclaimer: 'Notice: "This answer is generated by artificial intelligence and is based on current legislation. For an official legal opinion, please consult a lawyer."', copyright: "© 2026 My Lawyer - All rights reserved.", status: "published",
}

/** Shown until the admin publishes real FAQ content, so the section is never empty. */
const DEFAULT_FAQ: FAQData = {
  items: [
    // 1. პლატფორმის შესახებ
    { _id: "faq-1", question: "რას წარმოადგენს „ჩემი იურისტი“?", answer: "„ჩემი იურისტი“ არის ინოვაციური ონლაინ პლატფორმა, რომელიც ხელოვნური ინტელექტის (AI) დახმარებით სამართლებრივ პროცესებს მაქსიმალურად გიმარტივებთ.\nსაიტის მეშვეობით თქვენ შეგიძლიათ:\n– დაუსვათ კითხვები AI იურისტს და მიიღოთ მყისიერი პასუხები.\n– ავტომატურად დააგენერიროთ თქვენთვის სასურველი სამართლებრივი დოკუმენტები.\n– ატვირთოთ და შეამოწმოთ უკვე არსებული დოკუმენტები ხარვეზების აღმოსაჩენად.\nპლატფორმაზე ყველა პროცესი და გენერირებული პასუხი სრულად ეყრდნობა მოქმედ საქართველოს კანონმდებლობას.", category: "პლატფორმის შესახებ", order: 0, status: "published" },

    // 2. პაკეტები, ლიმიტები და ვადები
    { _id: "faq-2", question: "რა პაკეტებს გვთავაზობთ და როგორ ხდება გადახდა?", answer: "ჩვენ გვაქვს 4 სხვადასხვა პაკეტი: საბაზისო (უფასო), სტანდარტი, პრემიუმი და ინდივიდუალური.\nსტანდარტულ და პრემიუმ პაკეტებზე მოქმედებს ყოველთვიური გამოწერა.\nინდივიდუალურ პაკეტს ირჩევთ ერთჯერადად, თქვენი საჭიროების მიხედვით.", category: "პაკეტები, ლიმიტები და ვადები", order: 1, status: "published" },
    { _id: "faq-3", question: "როგორ მუშაობს საბაზისო (უფასო) პაკეტი?", answer: "საბაზისო პაკეტი სრულიად უფასოა.\nმისი გამოყენება შეგიძლიათ მანამ, სანამ მასზე დაწესებული ლიმიტები ბოლომდე არ ამოიწურება.", category: "პაკეტები, ლიმიტები და ვადები", order: 2, status: "published" },
    { _id: "faq-4", question: "რა ვადით აქტიურდება ფასიანი პაკეტები?", answer: "ყველა ფასიანი პაკეტის (სტანდარტი, პრემიუმი, ინდივიდუალური) მოქმედების ვადაა 1 თვე.\nყოველთვიური პაკეტები ავტომატურად განახლდება, ხოლო ინდივიდუალური პაკეტი უნდა შეიძინოთ ხელახლა, როცა დაგჭირდებათ.", category: "პაკეტები, ლიმიტები და ვადები", order: 3, status: "published" },
    { _id: "faq-5", question: "რა ხდება, თუ პაკეტის ლიმიტი ვადაზე ადრე ამოიწურა?", answer: "ლიმიტის ამოწურვის შემთხვევაში სისტემა მოგთხოვთ პაკეტის განახლებას.\nახალი პაკეტის შეძენისთანავე, 1-თვიანი ვადის ათვლა დაიწყება თავიდან, ზუსტად შეძენის დღიდან.", category: "პაკეტები, ლიმიტები და ვადები", order: 4, status: "published" },
    { _id: "faq-6", question: "შესაძლებელია თუ არა მიმდინარე პაკეტის შეცვლა?", answer: "დიახ, თქვენ ნებისმიერ დროს შეგიძლიათ შეცვალოთ თქვენი მიმდინარე პაკეტი (მაგალითად, გადახვიდეთ სტანდარტიდან პრემიუმზე).", category: "პაკეტები, ლიმიტები და ვადები", order: 5, status: "published" },

    // 3. პაკეტების კომბინირება
    { _id: "faq-7", question: "შესაძლებელია თუ არა რამდენიმე პაკეტის ერთდროულად ქონა?", answer: "დიახ, თქვენ შეგიძლიათ ერთდროულად გქონდეთ ყოველთვიური პაკეტიც (სტანდარტი ან პრემიუმი) და ერთჯერადი (ინდივიდუალური) პაკეტიც.", category: "პაკეტების კომბინირება", order: 6, status: "published" },
    { _id: "faq-8", question: "როგორ იხარჯება ლიმიტები, თუ ერთდროულად ორი პაკეტი მაქვს აქტიური?", answer: "ორივე პაკეტს ექნება თავისი დამოუკიდებელი ლიმიტები.\nსისტემა ავტომატურად პირველ რიგში დახარჯავს იმ პაკეტის ლიმიტს, რომლის მოქმედების ვადაც უფრო ადრე იწურება.", category: "პაკეტების კომბინირება", order: 7, status: "published" },

    // 4. ფასების ცვლილება და გადახდის უსაფრთხოება
    { _id: "faq-9", question: "სად ვნახო პაკეტების ზუსტი ღირებულება?", answer: "კონკრეტული ფასები ყოველთვის მითითებულია ჩვენს „ფასების გვერდზე“, სადაც ინფორმაცია მუდმივად ახლდება.", category: "ფასების ცვლილება და გადახდის უსაფრთხოება", order: 8, status: "published" },
    { _id: "faq-10", question: "რა მოხდება, თუ ჩემს პაკეტზე ფასდაკლება გამოცხადდება?", answer: "თუ თქვენ უკვე გაქვთ აქტიური ყოველთვიური გამოწერა და ამ პაკეტზე ფასდაკლება დაიწყება, მომდევნო თვიდან სისტემა ავტომატურად ჩამოგაჭრით შემცირებულ, ფასდაკლებულ თანხას.", category: "ფასების ცვლილება და გადახდის უსაფრთხოება", order: 9, status: "published" },
    { _id: "faq-11", question: "რა ხდება, თუ პაკეტების ფასი გაიზრდება?", answer: "ფასების ზოგადი გადახედვისა და გაზრდის შემთხვევაში, ინფორმაცია წინასწარ გეცნობებათ ყველა აქტიურ გამომწერს.", category: "ფასების ცვლილება და გადახდის უსაფრთხოება", order: 10, status: "published" },
    { _id: "faq-12", question: "გადახდის რა მეთოდებით შემიძლია სარგებლობა?", answer: "თქვენ შეგიძლიათ გადაიხადოთ ნებისმიერი ბანკის ბარათით.\nსისტემა მხარს უჭერს საგადახდო სისტემებს: Visa, Mastercard, Google Pay და Apple Pay.", category: "ფასების ცვლილება და გადახდის უსაფრთხოება", order: 11, status: "published" },
    { _id: "faq-13", question: "უსაფრთხოა თუ არა საიტზე გადახდების განხორციელება?", answer: "დიახ, გადახდები სრულიად უსაფრთხოა.\nსაიტი იყენებს თიბისი ბანკის უსაფრთხო საგადახდო სისტემას – Fleet, რაც უზრუნველყოფს თქვენი ტრანზაქციების მაქსიმალურ დაცვას.", category: "ფასების ცვლილება და გადახდის უსაფრთხოება", order: 12, status: "published" },

    // 5. გამოწერის გაუქმება და ანგარიშის მართვა
    { _id: "faq-14", question: "შემიძლია თუ არა გამოწერის გაუქმება?", answer: "დიახ, ყოველთვიური გამოწერის გაუქმება შეგიძლიათ ნებისმიერ დროს თქვენი პირადი პროფილიდან.", category: "გამოწერის გაუქმება და ანგარიშის მართვა", order: 13, status: "published" },
    { _id: "faq-15", question: "მივიღებ თუ არა თანხას უკან პაკეტის გაუქმების შემთხვევაში?", answer: "არა, გამოწერის გაუქმების შემთხვევაში გადახდილი თანხა უკან არ ბრუნდება.", category: "გამოწერის გაუქმება და ანგარიშის მართვა", order: 14, status: "published" },
    { _id: "faq-16", question: "როგორ შემიძლია ჩემი ანგარიშის (ექაუნთის) წაშლა?", answer: "თუ ანგარიშის წაშლა გსურთ, გამოგვიგზავნოთ მოთხოვნა ჩვენს ოფიციალურ ელექტრონულ ფოსტაზე და პროფილი მალევე გაუქმდება.", category: "გამოწერის გაუქმება და ანგარიშის მართვა", order: 15, status: "published" },
    { _id: "faq-17", question: "რა ემართება ჩემს მონაცემებს ანგარიშის წაშლის შემდეგ?", answer: "ანგარიშის გაუქმებისთანავე, თქვენი ყველა პირადი მონაცემი, ატვირთული ფაილი და ანალიზის ისტორია სამუდამოდ იშლება ჩვენი ბაზებიდან.", category: "გამოწერის გაუქმება და ანგარიშის მართვა", order: 16, status: "published" },

    // 6. მონაცემთა დაცვა და პერსონალური უსაფრთხოება
    { _id: "faq-18", question: "უსაფრთხოა თუ არა ჩემი დოკუმენტების ანალიზი?", answer: "დიახ, თქვენი უსაფრთხოება სრულად არის დაცული.\nდოკუმენტის ანალიზის პროცესში ყველა პირადი და სენსიტიური მონაცემი ავტომატურად იშიფრება.", category: "მონაცემთა დაცვა და პერსონალური უსაფრთხოება", order: 17, status: "published" },
    { _id: "faq-19", question: "კონკრეტულად რომელი მონაცემები იშიფრება ანალიზისას?", answer: "სისტემა შიფრავს ისეთ პირად ინფორმაციას, როგორიცაა: პირადი ნომერი, საიდენტიფიკაციო კოდი, ტელეფონის ნომერი, ელექტრონული ფოსტა და სხვა პერსონალური დეტალები.", category: "მონაცემთა დაცვა და პერსონალური უსაფრთხოება", order: 18, status: "published" },
    { _id: "faq-20", question: "გადაეცემა თუ არა ჩემი ატვირთული დოკუმენტები მესამე პირებს?", answer: "არა, თქვენი მონაცემები მკაცრად კონფიდენციალურია. ჩვენ არ ვუზიარებთ თქვენს დოკუმენტებს ან პირად ინფორმაციას არანაირ მესამე მხარეს.", category: "მონაცემთა დაცვა და პერსონალური უსაფრთხოება", order: 19, status: "published" },

    // 7. ხელოვნური ინტელექტის სიზუსტე და პასუხისმგებლობა
    { _id: "faq-21", question: "რამდენად ზუსტია ხელოვნური ინტელექტის მიერ გენერირებული პასუხები?", answer: "სისტემის მიერ გენერირებული ყველა პასუხი და დოკუმენტი ეყრდნობა მოქმედ კანონმდებლობას.\nთუმცა, ვინაიდან პროცესს ხელოვნური ინტელექტი მართავს, მიღებული შედეგები ყოველთვის უნდა განიხილოთ როგორც დამხმარე რეკომენდაცია.", category: "ხელოვნური ინტელექტის სიზუსტე და პასუხისმგებლობა", order: 20, status: "published" },
    { _id: "faq-22", question: "როგორ შემიძლია გადავამოწმო AI-ის მიერ მოწოდებული ინფორმაცია?", answer: "პასუხის ან დოკუმენტის გენერირების დროს სისტემა ყოველთვის უთითებს კონკრეტულ საკანონმდებლო წყაროებსა და მუხლებს, რაც საშუალებას გაძლევთ მარტივად გადაამოწმოთ ინფორმაცია.", category: "ხელოვნური ინტელექტის სიზუსტე და პასუხისმგებლობა", order: 21, status: "published" },
    { _id: "faq-23", question: "აქვს თუ არა პლატფორმის დოკუმენტებს ოფიციალური იურიდიული ძალა?", answer: "არა, ჩვენი პლატფორმა არის დამხმარე ინსტრუმენტი, რომელიც უბრალოდ უმარტივებს მომხმარებელს რუტინულ და რთულ პროცესებს.\nოფიციალური, იურიდიულად სავალდებულო დასკვნის მისაღებად აუცილებლად უნდა მიმართოთ კვალიფიციურ იურისტს.", category: "ხელოვნური ინტელექტის სიზუსტე და პასუხისმგებლობა", order: 22, status: "published" },
    { _id: "faq-24", question: "ვინ არის პასუხისმგებელი AI-ის მიერ დაშვებულ შესაძლო შეცდომებზე?", answer: "პლატფორმა შექმნილია საინფორმაციო და პროცესების გამარტივების მიზნით.\nსისტემის მიერ მომზადებული დოკუმენტების საბოლოო გამოყენებაზე, გადამოწმებასა და მიღებულ გადაწყვეტილებებზე პასუხისმგებლობა ეკისრება თავად მომხმარებელს.", category: "ხელოვნური ინტელექტის სიზუსტე და პასუხისმგებლობა", order: 23, status: "published" },

    // 8. ტექნიკური მხარდაჭერა და დახმარება
    { _id: "faq-25", question: "როგორ მოვიქცე ტექნიკური ხარვეზის ან კითხვების გაჩენის შემთხვევაში?", answer: "თუ მომსახურების პროცესში შეგექმნათ პრობლემა, შეგიძლიათ გამოიყენოთ საიტზე არსებული „ფიდბექის“ (Feedback) ღილაკი ან მოგვწეროთ პირდაპირ ელექტრონულ ფოსტაზე. ჩვენი გუნდი ოპერატიულად დაგეხმარებათ.", category: "ტექნიკური მხარდაჭერა და დახმარება", order: 24, status: "published" },

    // 9. რეგისტრაცია და ავტორიზაცია
    { _id: "faq-26", question: "როგორ შემიძლია პლატფორმაზე რეგისტრაცია?", answer: "რეგისტრაცია და საიტზე შესვლა შესაძლებელია როგორც Google-ის ანგარიშით, ასევე ელექტრონული ფოსტის (Email) საშუალებით.", category: "რეგისტრაცია და ავტორიზაცია", order: 25, status: "published" },
    { _id: "faq-27", question: "რა ვქნა, თუ პაროლი დამავიწყდა?", answer: "პაროლის აღდგენა შეგიძლიათ ავტორიზაციის (შესვლის) ფორმიდან „პაროლის აღდგენის“ ღილაკით. გაითვალისწინეთ, რომ აღდგენის კოდი ხშირად სპამში (Spam) ვარდება, ამიტომ შეამოწმეთ ეს საქაღალდეც.", category: "რეგისტრაცია და ავტორიზაცია", order: 26, status: "published" },
    { _id: "faq-28", question: "შესაძლებელია თუ არა პაროლის შეცვლა საიტიდან?", answer: "დიახ, მიმდინარე პაროლის შეცვლა ნებისმიერ დროს შეგიძლიათ თქვენი პირადი პროფილის პარამეტრებიდან.", category: "რეგისტრაცია და ავტორიზაცია", order: 27, status: "published" },

    // 10. ფაილების ფორმატები და ატვირთვა
    { _id: "faq-29", question: "რა ფორმატის ფაილების ატვირთვაა შესაძლებელი საიტზე?", answer: "დოკუმენტების შემოწმებისა და ანალიზისთვის შეგიძლიათ ატვირთოთ PDF, DOCX, TXT, MD და JPG (ფოტო) ფორმატის ფაილები.", category: "ფაილების ფორმატები და ატვირთვა", order: 28, status: "published" },
    { _id: "faq-30", question: "რა ფორმატში ხდება მზა დოკუმენტების ჩამოტვირთვა?", answer: "გენერირებული სამართლებრივი დოკუმენტების ჩამოტვირთვა შეგიძლიათ Word (DOCX) ან PDF ფორმატებში.", category: "ფაილების ფორმატები და ატვირთვა", order: 29, status: "published" },
  ],
}

const DEFAULT_FAQ_EN: FAQData = {
  items: [
    { _id: "faq-1", question: "What is \"My Lawyer\"?", answer: "A platform where you ask an AI lawyer questions, generate legal document templates, and get an existing document reviewed — all grounded in current Georgian legislation.", category: "general", order: 0, status: "published" },
    { _id: "faq-2", question: "Does the AI answer replace a real lawyer?", answer: "No. Answers are based on current legislation, but are not an official legal opinion — consult a licensed lawyer for your specific case.", category: "general", order: 1, status: "published" },
    { _id: "faq-3", question: "What's included in the free plan?", answer: "The Basic plan includes a limited number of monthly AI consultations, document template generation, and document review — no card required.", category: "billing", order: 2, status: "published" },
    { _id: "faq-4", question: "How do I cancel or change my subscription?", answer: "From your profile's Billing section you can upgrade, change, or cancel your plan at any time.", category: "billing", order: 3, status: "published" },
  ],
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toPlain<T>(doc: T): T {
  if (!doc) return doc
  const obj = JSON.parse(JSON.stringify(doc)) as T
  return obj
}

// ─── Public Getters ───────────────────────────────────────────────────────────

export async function getSiteConfig(locale: Locale = "ka"): Promise<SiteConfigData> {
  const fallback = locale === "en" ? DEFAULT_SITE_CONFIG_EN : DEFAULT_SITE_CONFIG
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await SiteConfig.findOne({ locale: "en" }).lean()
      : await SiteConfig.findOne({ locale: { $ne: "en" } }).lean() ?? await SiteConfig.findOne().lean()
    if (!doc) return fallback
    return toPlain({
      logoUrl: doc.logoUrl, logoPubId: doc.logoPubId, siteName: doc.siteName,
      tagline: doc.tagline, favicon: doc.favicon, contactEmail: doc.contactEmail,
      contactPhone: doc.contactPhone, contactPhoneVisible: doc.contactPhoneVisible ?? false,
      contactAddress: doc.contactAddress,
      socialLinks: doc.socialLinks ?? {},
    })
  } catch { return fallback }
}

export async function getNavMenu(locale: Locale = "ka"): Promise<NavMenuData> {
  const fallback = locale === "en" ? DEFAULT_NAV_EN : DEFAULT_NAV
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await NavMenu.findOne({ status: "published", locale: "en" }).lean()
      : await NavMenu.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return fallback
    return toPlain({
      items: doc.items.map((i) => ({
        _id: String(i._id), label: i.label, href: i.href, order: i.order, isExternal: i.isExternal,
      })).sort((a, b) => a.order - b.order),
      status: doc.status as "published",
    })
  } catch { return fallback }
}

const INFORMAL_PRICING = "აირჩიე თქვენზე მორგებული პაკეტი"
const INFORMAL_CARD_SUBTITLES: Record<string, string> = {
  "დასვი კითხვა":        "დასვით კითხვა",
  "შექმენი შაბლონი":    "შექმენით შაბლონი",
  "შეამოწმე დოკუმენტი": "შეამოწმეთ დოკუმენტი",
}
const INFORMAL_CARD_CTA: Record<string, string> = {
  "შექმენი დოკუმენტი": "შექმენით დოკუმენტი",
}

export async function getHomePage(): Promise<HomePageData | null> {
  try {
    await dbConnect()
    const doc = await HomePage.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return null
    const data = toPlain(doc as unknown as HomePageData)
    if (data.pricingHeading === INFORMAL_PRICING) {
      data.pricingHeading = HOME_SEED.pricingHeading
    }
    if (data.serviceCards?.length) {
      data.serviceCards = data.serviceCards.map((card) => ({
        ...card,
        subtitle:  INFORMAL_CARD_SUBTITLES[card.subtitle]  ?? card.subtitle,
        ctaText:   INFORMAL_CARD_CTA[card.ctaText ?? ""]   ?? card.ctaText,
        // Pre-launch "Documents" card pointed at the placeholder /docs route;
        // it's now the document analysis modal trigger.
        // Pre-launch "Templates" card pointed at the placeholder /templates route,
        // which never existed; the feature lives at /generate.
        href:
          card.href === "/docs" ? "/review" :
          card.href === "/templates" ? "/generate" :
          card.href,
        comingSoon: card.href === "/docs" || card.href === "/templates" ? false : card.comingSoon,
      }))
    }
    return data
  } catch { return null }
}

export async function getAboutPage(locale: Locale = "ka"): Promise<AboutPageData | null> {
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await AboutPage.findOne({ status: "published", locale: "en" }).lean()
      : await AboutPage.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return null
    return toPlain(doc as unknown as AboutPageData)
  } catch { return null }
}

export async function getFAQ(locale: Locale = "ka"): Promise<FAQData> {
  const fallback = locale === "en" ? DEFAULT_FAQ_EN : DEFAULT_FAQ
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await FAQ.findOne({ locale: "en" }).lean()
      : await FAQ.findOne({ locale: { $ne: "en" } }).lean() ?? await FAQ.findOne().lean()
    if (!doc) return fallback
    const items = doc.items
      .filter((i) => i.status === "published")
      .sort((a, b) => a.order - b.order)
      .map((i) => ({ _id: String(i._id), question: i.question, answer: i.answer, category: i.category, order: i.order, status: i.status as import("@/types/cms").CMSStatus }))
    return items.length > 0 ? toPlain({ items }) : fallback
  } catch { return fallback }
}

export async function getFooter(locale: Locale = "ka"): Promise<FooterData> {
  const fallback = locale === "en" ? DEFAULT_FOOTER_EN : DEFAULT_FOOTER
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await FooterContent.findOne({ status: "published", locale: "en" }).lean()
      : await FooterContent.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return fallback
    return toPlain(doc as unknown as FooterData)
  } catch { return fallback }
}

export async function getLegalNotice(type: LegalNoticeType, locale: Locale = "ka"): Promise<LegalNoticeData | null> {
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await LegalNotice.findOne({ type, status: "published", locale: "en" }).lean()
      : await LegalNotice.findOne({ type, status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return null
    return toPlain({
      _id: String(doc._id), type: doc.type as import("@/types/cms").LegalNoticeType, title: doc.title, body: doc.body,
      status: doc.status as import("@/types/cms").CMSStatus, publishedAt: doc.publishedAt ? doc.publishedAt.toISOString() : null,
    }) as LegalNoticeData
  } catch { return null }
}
