import { dbConnect } from "@/lib/db"
import { HOME_SEED } from "@/lib/homepage-defaults"
import { SiteConfig } from "@/lib/models/SiteConfig"
import { NavMenu } from "@/lib/models/NavMenu"
import { HomePage } from "@/lib/models/HomePage"
import { AboutPage } from "@/lib/models/AboutPage"
import { FAQ } from "@/lib/models/FAQ"
import { FooterContent } from "@/lib/models/FooterContent"
import { LegalNotice } from "@/lib/models/LegalNotice"
import { BlogPost } from "@/lib/models/BlogPost"
import type {
  SiteConfigData, NavMenuData, HomePageData, AboutPageData,
  FAQData, FooterData, LegalNoticeData, LegalNoticeType, BlogPostData,
} from "@/types/cms"
import type { Locale } from "@/lib/i18n/config"

/** Mongo filter selecting the requested locale's docs (ka = anything not "en"). */
function localeMatch(locale: Locale) {
  return locale === "en" ? { locale: "en" } : { locale: { $ne: "en" } }
}

// ─── Defaults ────────────────────────────────────────────────────────────────

const DEFAULT_SITE_CONFIG: SiteConfigData = {
  logoUrl: "", logoPubId: "", siteName: "ჩემი იურისტი", tagline: "",
  favicon: "", contactEmail: "", contactPhone: "", contactAddress: "", socialLinks: {},
}

const DEFAULT_NAV: NavMenuData = {
  items: [
    { _id: "1", label: "მთავარი", href: "/", order: 0, isExternal: false },
    { _id: "2", label: "ჩვენ შესახებ", href: "/about", order: 1, isExternal: false },
    { _id: "3", label: "მომსახურებები", href: "/services", order: 2, isExternal: false },
    { _id: "4", label: "კანონმდებლობა", href: "/legislation", order: 3, isExternal: false },
    { _id: "5", label: "ბლოგი", href: "/blog", order: 4, isExternal: false },
  ],
  status: "published",
}

const DEFAULT_FOOTER: FooterData = {
  columns: [], disclaimer: 'გაფრთხილება: „პასუხი გენერირებულია ხელოვნური ინტელექტის მიერ და ეფუძნება მოქმედ კანონმდებლობას. ოფიციალური იურიდიული დასკვნისთვის მიმართეთ იურისტს."', copyright: "© 2026 ჩემი იურისტი - ყველა უფლება დაცულია.", status: "published",
}

const DEFAULT_SITE_CONFIG_EN: SiteConfigData = {
  logoUrl: "", logoPubId: "", siteName: "My Lawyer", tagline: "Law in plain language",
  favicon: "", contactEmail: "", contactPhone: "", contactAddress: "", socialLinks: {},
}

const DEFAULT_NAV_EN: NavMenuData = {
  items: [
    { _id: "1", label: "Home", href: "/", order: 0, isExternal: false },
    { _id: "2", label: "About us", href: "/about", order: 1, isExternal: false },
    { _id: "3", label: "Services", href: "/services", order: 2, isExternal: false },
    { _id: "4", label: "Legislation", href: "/legislation", order: 3, isExternal: false },
    { _id: "5", label: "Blog", href: "/blog", order: 4, isExternal: false },
  ],
  status: "published",
}

const DEFAULT_FOOTER_EN: FooterData = {
  columns: [], disclaimer: 'Notice: "This answer is generated by artificial intelligence and is based on current legislation. For an official legal opinion, please consult a lawyer."', copyright: "© 2026 My Lawyer - All rights reserved.", status: "published",
}

/** Shown until the admin publishes real FAQ content, so the section is never empty. */
const DEFAULT_FAQ: FAQData = {
  items: [
    { _id: "faq-1", question: "რას წარმოადგენს „ჩემი იურისტი“?", answer: "პლატფორმა, სადაც AI იურისტს კითხვას სვამთ, სამართლებრივ დოკუმენტებს ავტომატურად აგენერირებთ და უკვე არსებულ დოკუმენტს შემოწმებაზე აგზავნით — ყველაფერი მოქმედ საქართველოს კანონმდებლობაზე დაყრდნობით.", category: "general", order: 0, status: "published" },
    { _id: "faq-2", question: "შემიცვლის თუ არა AI პასუხი რეალურ იურისტს?", answer: "არა. პასუხები ეფუძნება მოქმედ კანონმდებლობას, მაგრამ არ წარმოადგენს ოფიციალურ იურიდიულ დასკვნას — კონკრეტული საკითხისთვის მიმართეთ ლიცენზირებულ იურისტს.", category: "general", order: 1, status: "published" },
    { _id: "faq-3", question: "რა შედის უფასო პაკეტში?", answer: "საბაზისო პაკეტი გთავაზობთ თვეში შეზღუდულ რაოდენობის AI კონსულტაციას, დოკუმენტის შაბლონის გენერირებას და დოკუმენტის შემოწმებას — ბარათის გარეშე.", category: "billing", order: 2, status: "published" },
    { _id: "faq-4", question: "როგორ გავააუქმო ან შევცვალო გამოწერა?", answer: "პროფილის გვერდიდან „ბილინგის“ სექციაში შეგიძლიათ პაკეტის განახლება, შეცვლა ან გაუქმება ნებისმიერ დროს.", category: "billing", order: 3, status: "published" },
  ],
}

const DEFAULT_FAQ_EN: FAQData = {
  items: [
    { _id: "faq-1", question: "What is \"My Lawyer\"?", answer: "A platform where you ask an AI lawyer questions, generate legal document templates, and get an existing document reviewed — all grounded in current Georgian legislation.", category: "general", order: 0, status: "published" },
    { _id: "faq-2", question: "Does the AI answer replace a real lawyer?", answer: "No. Answers are based on current legislation, but are not an official legal opinion — consult a licensed lawyer for your specific case.", category: "general", order: 1, status: "published" },
    { _id: "faq-3", question: "What's included in the free plan?", answer: "The Basic plan includes a limited number of monthly AI consultations, document template generation, and document review — no card required.", category: "billing", order: 2, status: "published" },
    { _id: "faq-4", question: "How do I cancel or change my subscription?", answer: "From your profile's Billing section you can upgrade, change, or cancel your plan at any time.", category: "billing", order: 3, status: "published" },
  ],
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function toPlain<T>(doc: T): T {
  if (!doc) return doc
  const obj = JSON.parse(JSON.stringify(doc)) as T
  return obj
}

// ─── Public Getters ───────────────────────────────────────────────────────────

export async function getSiteConfig(locale: Locale = "ka"): Promise<SiteConfigData> {
  const fallback = locale === "en" ? DEFAULT_SITE_CONFIG_EN : DEFAULT_SITE_CONFIG
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await SiteConfig.findOne({ locale: "en" }).lean()
      : await SiteConfig.findOne({ locale: { $ne: "en" } }).lean() ?? await SiteConfig.findOne().lean()
    if (!doc) return fallback
    return toPlain({
      logoUrl: doc.logoUrl, logoPubId: doc.logoPubId, siteName: doc.siteName,
      tagline: doc.tagline, favicon: doc.favicon, contactEmail: doc.contactEmail,
      contactPhone: doc.contactPhone, contactAddress: doc.contactAddress,
      socialLinks: doc.socialLinks ?? {},
    })
  } catch { return fallback }
}

export async function getNavMenu(locale: Locale = "ka"): Promise<NavMenuData> {
  const fallback = locale === "en" ? DEFAULT_NAV_EN : DEFAULT_NAV
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await NavMenu.findOne({ status: "published", locale: "en" }).lean()
      : await NavMenu.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return fallback
    return toPlain({
      items: doc.items.map((i) => ({
        _id: String(i._id), label: i.label, href: i.href, order: i.order, isExternal: i.isExternal,
      })).sort((a, b) => a.order - b.order),
      status: doc.status as "published",
    })
  } catch { return fallback }
}

const INFORMAL_PRICING = "აირჩიე თქვენზე მორგებული პაკეტი"
const INFORMAL_CTA_TITLE = "მზად ხარ?"
const INFORMAL_CARD_SUBTITLES: Record<string, string> = {
  "დასვი კითხვა":        "დასვით კითხვა",
  "შექმენი შაბლონი":    "შექმენით შაბლონი",
  "შეამოწმე დოკუმენტი": "შეამოწმეთ დოკუმენტი",
}
const INFORMAL_CARD_CTA: Record<string, string> = {
  "შექმენი დოკუმენტი": "შექმენით დოკუმენტი",
}

export async function getHomePage(): Promise<HomePageData | null> {
  try {
    await dbConnect()
    const doc = await HomePage.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return null
    const data = toPlain(doc as unknown as HomePageData)
    if (data.pricingHeading === INFORMAL_PRICING) {
      data.pricingHeading = HOME_SEED.pricingHeading
    }
    if (data.ctaSection?.title === INFORMAL_CTA_TITLE) {
      data.ctaSection = { ...data.ctaSection, ...HOME_SEED.ctaSection }
    }
    if (data.serviceCards?.length) {
      data.serviceCards = data.serviceCards.map((card) => ({
        ...card,
        subtitle:  INFORMAL_CARD_SUBTITLES[card.subtitle]  ?? card.subtitle,
        ctaText:   INFORMAL_CARD_CTA[card.ctaText ?? ""]   ?? card.ctaText,
        // Pre-launch "Documents" card pointed at the placeholder /docs route;
        // it's now the document analysis modal trigger.
        // Pre-launch "Templates" card pointed at the placeholder /templates route,
        // which never existed; the feature lives at /generate.
        href:
          card.href === "/docs" ? "/review" :
          card.href === "/templates" ? "/generate" :
          card.href,
        comingSoon: card.href === "/docs" || card.href === "/templates" ? false : card.comingSoon,
      }))
    }
    return data
  } catch { return null }
}

export async function getAboutPage(locale: Locale = "ka"): Promise<AboutPageData | null> {
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await AboutPage.findOne({ status: "published", locale: "en" }).lean()
      : await AboutPage.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return null
    return toPlain(doc as unknown as AboutPageData)
  } catch { return null }
}

export async function getFAQ(locale: Locale = "ka"): Promise<FAQData> {
  const fallback = locale === "en" ? DEFAULT_FAQ_EN : DEFAULT_FAQ
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await FAQ.findOne({ locale: "en" }).lean()
      : await FAQ.findOne({ locale: { $ne: "en" } }).lean() ?? await FAQ.findOne().lean()
    if (!doc) return fallback
    const items = doc.items
      .filter((i) => i.status === "published")
      .sort((a, b) => a.order - b.order)
      .map((i) => ({ _id: String(i._id), question: i.question, answer: i.answer, category: i.category, order: i.order, status: i.status as import("@/types/cms").CMSStatus }))
    return items.length > 0 ? toPlain({ items }) : fallback
  } catch { return fallback }
}

export async function getFooter(locale: Locale = "ka"): Promise<FooterData> {
  const fallback = locale === "en" ? DEFAULT_FOOTER_EN : DEFAULT_FOOTER
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await FooterContent.findOne({ status: "published", locale: "en" }).lean()
      : await FooterContent.findOne({ status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return fallback
    return toPlain(doc as unknown as FooterData)
  } catch { return fallback }
}

export async function getLegalNotice(type: LegalNoticeType, locale: Locale = "ka"): Promise<LegalNoticeData | null> {
  try {
    await dbConnect()
    const doc = locale === "en"
      ? await LegalNotice.findOne({ type, status: "published", locale: "en" }).lean()
      : await LegalNotice.findOne({ type, status: "published", locale: { $ne: "en" } }).lean()
    if (!doc) return null
    return toPlain({
      _id: String(doc._id), type: doc.type as import("@/types/cms").LegalNoticeType, title: doc.title, body: doc.body,
      status: doc.status as import("@/types/cms").CMSStatus, publishedAt: doc.publishedAt ? doc.publishedAt.toISOString() : null,
    }) as LegalNoticeData
  } catch { return null }
}

export async function getPublishedBlogPosts(locale: Locale = "ka", limit = 20): Promise<BlogPostData[]> {
  try {
    await dbConnect()
    let docs = await BlogPost.find({ status: "published", ...localeMatch(locale) })
      .sort({ publishedAt: -1 }).limit(limit).lean()
    if (locale === "en" && docs.length === 0) {
      docs = await BlogPost.find({ status: "published", locale: { $ne: "en" } })
        .sort({ publishedAt: -1 }).limit(limit).lean()
    }
    return toPlain(docs.map((d) => ({
      _id: String(d._id), title: d.title, slug: d.slug, body: d.body,
      excerpt: d.excerpt, coverImageUrl: d.coverImageUrl, coverImagePubId: d.coverImagePubId,
      category: String(d.category), tags: d.tags, author: d.author, status: d.status as import("@/types/cms").CMSStatus,
      publishedAt: d.publishedAt ? d.publishedAt.toISOString() : null,
      createdAt: (d as { createdAt?: Date }).createdAt?.toISOString() ?? "",
    })))
  } catch { return [] }
}

export async function getBlogPost(slug: string): Promise<BlogPostData | null> {
  try {
    await dbConnect()
    const doc = await BlogPost.findOne({ slug, status: "published" }).lean()
    if (!doc) return null
    return toPlain({
      _id: String(doc._id), title: doc.title, slug: doc.slug, body: doc.body,
      excerpt: doc.excerpt, coverImageUrl: doc.coverImageUrl, coverImagePubId: doc.coverImagePubId,
      category: String(doc.category), tags: doc.tags, author: doc.author, status: doc.status as import("@/types/cms").CMSStatus,
      publishedAt: doc.publishedAt ? doc.publishedAt.toISOString() : null,
      createdAt: (doc as { createdAt?: Date }).createdAt?.toISOString() ?? "",
    }) as BlogPostData
  } catch { return null }
}
