export type FieldType = "text" | "textarea" | "date";
export type QuestionField = { key: string; label: string; type: FieldType; required?: boolean };

export const COMMON_FIELDS: QuestionField[] = [
  { key: "city", label: "ქალაქი", type: "text", required: true },
  { key: "docDate", label: "დოკუმენტის თარიღი", type: "date", required: true },
];

export const QUESTION_SCHEMAS: Record<string, QuestionField[]> = {
  complaint: [
    { key: "yourName", label: "შენი სახელი და გვარი", type: "text", required: true },
    { key: "yourId", label: "შენი პირადი ნომერი", type: "text", required: true },
    { key: "yourAddress", label: "შენი მისამართი", type: "text", required: true },
    { key: "respondent", label: "ვის ეხება საჩივარი", type: "text", required: true },
    { key: "amount", label: "თანხა/ზიანი (ასეთის არსებობისას)", type: "text" },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა) — თანხის მოთხოვნისას", type: "text" },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვას ითხოვ)", type: "text" },
    { key: "incidentDate", label: "მოვლენის თარიღი", type: "date" },
  ],
  "rental-agreement": [
    { key: "landlord", label: "გამქირავებელი (სახელი, გვარი)", type: "text", required: true },
    { key: "landlordId", label: "გამქირავებლის პირადი ნომერი", type: "text", required: true },
    { key: "landlordAddress", label: "გამქირავებლის მისამართი", type: "text", required: true },
    { key: "landlordPhone", label: "გამქირავებლის ტელეფონი", type: "text" },
    { key: "tenant", label: "დამქირავებელი (სახელი, გვარი)", type: "text", required: true },
    { key: "tenantId", label: "დამქირავებლის პირადი ნომერი", type: "text", required: true },
    { key: "tenantAddress", label: "დამქირავებლის მისამართი", type: "text", required: true },
    { key: "tenantPhone", label: "დამქირავებლის ტელეფონი", type: "text" },
    { key: "address", label: "ბინის მისამართი", type: "text", required: true },
    { key: "rent", label: "ქირის ოდენობა", type: "text", required: true },
    { key: "paymentMethod", label: "ქირის გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვაა)", type: "text" },
    { key: "duration", label: "ხელშეკრულების ვადა", type: "text", required: true },
  ],
  "employment-contract": [
    { key: "employer", label: "დამსაქმებელი", type: "text", required: true },
    { key: "employerId", label: "დამსაქმებლის საიდენტიფიკაციო/პირადი ნომერი", type: "text", required: true },
    { key: "employerAddress", label: "დამსაქმებლის მისამართი", type: "text", required: true },
    { key: "employee", label: "თანამშრომელი", type: "text", required: true },
    { key: "employeeId", label: "თანამშრომლის პირადი ნომერი", type: "text", required: true },
    { key: "employeeAddress", label: "თანამშრომლის მისამართი", type: "text", required: true },
    { key: "position", label: "პოზიცია", type: "text", required: true },
    { key: "salary", label: "ხელფასი", type: "text", required: true },
    { key: "salaryPaymentMethod", label: "ხელფასის გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", type: "text", required: true },
    { key: "bankAccount", label: "თანამშრომლის საბანკო ანგარიშის № (თუ გადარიცხვაა)", type: "text" },
    { key: "startDate", label: "დაწყების თარიღი", type: "date", required: true },
  ],
  "power-of-attorney": [
    { key: "principal", label: "მინდობელი", type: "text", required: true },
    { key: "idNumber", label: "მინდობელის პირადი ნომერი", type: "text", required: true },
    { key: "principalAddress", label: "მინდობელის მისამართი", type: "text", required: true },
    { key: "agent", label: "მინდობილი პირი", type: "text", required: true },
    { key: "agentId", label: "მინდობილი პირის პირადი ნომერი", type: "text", required: true },
    { key: "agentAddress", label: "მინდობილი პირის მისამართი", type: "text", required: true },
    { key: "scope", label: "მინდობის ფარგლები", type: "textarea", required: true },
  ],
  "demand-letter": [
    { key: "yourName", label: "შენი სახელი და გვარი", type: "text", required: true },
    { key: "yourAddress", label: "შენი მისამართი", type: "text", required: true },
    { key: "recipient", label: "ადრესატი", type: "text", required: true },
    { key: "amount", label: "მოთხოვნილი თანხა", type: "text" },
    { key: "paymentMethod", label: "გადახდის სასურველი მეთოდი (ნაღდი/საბანკო გადარიცხვა)", type: "text" },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვას ითხოვ)", type: "text" },
    { key: "reason", label: "მოთხოვნის საფუძველი", type: "textarea", required: true },
    { key: "deadline", label: "ვადა", type: "text", required: true },
  ],
  "termination-notice": [
    { key: "employer", label: "დამსაქმებელი", type: "text", required: true },
    { key: "employee", label: "თანამშრომელი", type: "text", required: true },
    { key: "employeeId", label: "თანამშრომლის პირადი ნომერი", type: "text", required: true },
    { key: "employeeAddress", label: "თანამშრომლის მისამართი", type: "text", required: true },
    { key: "reason", label: "საფუძველი", type: "text", required: true },
    { key: "lastDay", label: "ბოლო სამუშაო დღე", type: "date", required: true },
  ],
  "service-agreement": [
    { key: "executor", label: "შემსრულებელი (სახელი, გვარი / დასახელება)", type: "text", required: true },
    { key: "executorId", label: "შემსრულებლის პირადი/საიდენტიფიკაციო № ", type: "text", required: true },
    { key: "executorAddress", label: "შემსრულებლის მისამართი", type: "text", required: true },
    { key: "executorPhone", label: "შემსრულებლის ტელეფონი", type: "text" },
    { key: "client", label: "დამკვეთი (სახელი, გვარი / დასახელება)", type: "text", required: true },
    { key: "clientId", label: "დამკვეთის პირადი/საიდენტიფიკაციო №", type: "text", required: true },
    { key: "clientAddress", label: "დამკვეთის მისამართი", type: "text", required: true },
    { key: "clientPhone", label: "დამკვეთის ტელეფონი", type: "text" },
    { key: "serviceDescription", label: "მომსახურების აღწერა", type: "textarea", required: true },
    { key: "deadline", label: "მომსახურების ვადა/ვადები", type: "text", required: true },
    { key: "price", label: "საფასური", type: "text", required: true },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვაა)", type: "text" },
  ],
  "claim-letter": [
    { key: "senderName", label: "გამომგზავნის სახელი და გვარი", type: "text", required: true },
    { key: "senderId", label: "გამომგზავნის პირადი ნომერი", type: "text" },
    { key: "senderAddress", label: "გამომგზავნის მისამართი", type: "text", required: true },
    { key: "senderPhone", label: "გამომგზავნის ტელეფონი", type: "text" },
    { key: "recipientName", label: "ადრესატი (ვის ეგზავნება პრეტენზია)", type: "text", required: true },
    { key: "recipientAddress", label: "ადრესატის მისამართი", type: "text" },
    { key: "grounds", label: "პრეტენზიის ფაქტობრივი საფუძველი", type: "textarea", required: true },
    { key: "demand", label: "კონკრეტული მოთხოვნა", type: "textarea", required: true },
    { key: "amount", label: "მოთხოვნილი თანხა (ასეთის არსებობისას)", type: "text" },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", type: "text" },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვას ითხოვ)", type: "text" },
    { key: "deadline", label: "პასუხის/შესრულების ვადა", type: "text", required: true },
  ],
  "debt-claim": [
    { key: "creditorName", label: "კრედიტორის სახელი და გვარი", type: "text", required: true },
    { key: "creditorId", label: "კრედიტორის პირადი ნომერი", type: "text" },
    { key: "creditorAddress", label: "კრედიტორის მისამართი", type: "text", required: true },
    { key: "creditorPhone", label: "კრედიტორის ტელეფონი", type: "text" },
    { key: "debtorName", label: "მოვალის სახელი და გვარი", type: "text", required: true },
    { key: "debtorAddress", label: "მოვალის მისამართი", type: "text", required: true },
    { key: "debtBasis", label: "დავალიანების საფუძველი (სესხის ხელშეკრულება, ხელწერილი, თარიღი და სხვ.)", type: "textarea", required: true },
    { key: "principalAmount", label: "ძირითადი თანხა", type: "text", required: true },
    { key: "interestAmount", label: "დარიცხული პროცენტი/პირგასამტეხლო (ასეთის არსებობისას)", type: "text" },
    { key: "totalAmount", label: "სულ გადასახდელი თანხა", type: "text", required: true },
    { key: "originalDueDate", label: "დაბრუნების თავდაპირველი ვადა", type: "date" },
    { key: "newDeadline", label: "ახალი ვადა დაფარვისთვის", type: "text", required: true },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის №", type: "text" },
  ],
  "child-travel-consent": [
    { key: "parentName", label: "თანხმობის გამცემი მშობლის/კანონიერი წარმომადგენლის სახელი და გვარი", type: "text", required: true },
    { key: "parentId", label: "მშობლის პირადი ნომერი", type: "text", required: true },
    { key: "parentAddress", label: "მშობლის მისამართი", type: "text", required: true },
    { key: "parentPhone", label: "მშობლის ტელეფონი", type: "text" },
    { key: "childName", label: "არასრულწლოვნის სახელი და გვარი", type: "text", required: true },
    { key: "childDob", label: "არასრულწლოვნის დაბადების თარიღი", type: "date", required: true },
    { key: "childDocument", label: "არასრულწლოვნის პირადობის/პასპორტის № ", type: "text", required: true },
    { key: "escort", label: "თანმხლები პირი (სახელი, გვარი, პ/ნ) ან „დამოუკიდებლად“", type: "text", required: true },
    { key: "destination", label: "დანიშნულების ქვეყანა/ქვეყნები", type: "text", required: true },
    { key: "travelPeriod", label: "მოგზაურობის პერიოდი", type: "text", required: true },
  ],
  invoice: [
    { key: "invoiceNumber", label: "ინვოისის №", type: "text", required: true },
    { key: "seller", label: "გამომწერი (გამყიდველი/მომსახურების მიმწოდებელი)", type: "text", required: true },
    { key: "sellerId", label: "გამომწერის საიდენტიფიკაციო/პირადი №", type: "text" },
    { key: "sellerAddress", label: "გამომწერის მისამართი", type: "text" },
    { key: "buyer", label: "მიმღები (გადამხდელი)", type: "text", required: true },
    { key: "buyerAddress", label: "მიმღების მისამართი", type: "text" },
    { key: "items", label: "საქონელი/მომსახურება", type: "textarea", required: true },
    { key: "totalAmount", label: "სულ გადასახდელი თანხა", type: "text", required: true },
    { key: "dueDate", label: "გადახდის ვადა", type: "date", required: true },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის №", type: "text" },
  ],
  "acceptance-act": [
    { key: "actNumber", label: "აქტის №", type: "text" },
    { key: "provider", label: "მიმცემი მხარე (შემსრულებელი/მიმწოდებელი)", type: "text", required: true },
    { key: "providerId", label: "მიმცემის საიდენტიფიკაციო/პირადი №", type: "text" },
    { key: "providerAddress", label: "მიმცემის მისამართი", type: "text" },
    { key: "receiver", label: "მიმღები მხარე (დამკვეთი)", type: "text", required: true },
    { key: "receiverId", label: "მიმღების საიდენტიფიკაციო/პირადი №", type: "text" },
    { key: "receiverAddress", label: "მიმღების მისამართი", type: "text" },
    { key: "contractRef", label: "საბაზისო ხელშეკრულების რეკვიზიტები (№, თარიღი)", type: "text" },
    { key: "subjectDescription", label: "ჩაბარებული საქონლის/სამუშაოს/მომსახურების აღწერა", type: "textarea", required: true },
    { key: "amount", label: "ღირებულება", type: "text" },
    { key: "objections", label: "მხარეთა შენიშვნები/პრეტენზიები (ასეთის არარსებობისას — „არ არსებობს“)", type: "textarea", required: true },
  ],
};
