import type { Locale } from "@/lib/i18n/config";

export type FieldType = "text" | "textarea" | "date";
export type QuestionField = { key: string; label: string; labelEn: string; type: FieldType; required?: boolean };

export const COMMON_FIELDS: QuestionField[] = [
  { key: "city", label: "ქალაქი", labelEn: "City", type: "text", required: true },
  { key: "docDate", label: "დოკუმენტის თარიღი", labelEn: "Document date", type: "date", required: true },
];

export const QUESTION_SCHEMAS: Record<string, QuestionField[]> = {
  complaint: [
    { key: "yourName", label: "შენი სახელი და გვარი", labelEn: "Your full name", type: "text", required: true },
    { key: "yourId", label: "შენი პირადი ნომერი", labelEn: "Your personal number", type: "text", required: true },
    { key: "yourAddress", label: "შენი მისამართი", labelEn: "Your address", type: "text", required: true },
    { key: "respondent", label: "ვის ეხება საჩივარი", labelEn: "Who the complaint concerns", type: "text", required: true },
    { key: "amount", label: "თანხა/ზიანი (ასეთის არსებობისას)", labelEn: "Amount/damages (if any)", type: "text" },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა) — თანხის მოთხოვნისას", labelEn: "Payment method (cash/bank transfer) — if requesting payment", type: "text" },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვას ითხოვ)", labelEn: "Bank account No. (if requesting a transfer)", type: "text" },
    { key: "incidentDate", label: "მოვლენის თარიღი", labelEn: "Date of incident", type: "date" },
  ],
  "rental-agreement": [
    { key: "landlord", label: "გამქირავებელი (სახელი, გვარი)", labelEn: "Landlord (full name)", type: "text", required: true },
    { key: "landlordId", label: "გამქირავებლის პირადი ნომერი", labelEn: "Landlord's personal number", type: "text", required: true },
    { key: "landlordAddress", label: "გამქირავებლის მისამართი", labelEn: "Landlord's address", type: "text", required: true },
    { key: "landlordPhone", label: "გამქირავებლის ტელეფონი", labelEn: "Landlord's phone number", type: "text" },
    { key: "tenant", label: "დამქირავებელი (სახელი, გვარი)", labelEn: "Tenant (full name)", type: "text", required: true },
    { key: "tenantId", label: "დამქირავებლის პირადი ნომერი", labelEn: "Tenant's personal number", type: "text", required: true },
    { key: "tenantAddress", label: "დამქირავებლის მისამართი", labelEn: "Tenant's address", type: "text", required: true },
    { key: "tenantPhone", label: "დამქირავებლის ტელეფონი", labelEn: "Tenant's phone number", type: "text" },
    { key: "address", label: "ბინის მისამართი", labelEn: "Property address", type: "text", required: true },
    { key: "rent", label: "ქირის ოდენობა", labelEn: "Rent amount", type: "text", required: true },
    { key: "paymentMethod", label: "ქირის გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", labelEn: "Rent payment method (cash/bank transfer)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვაა)", labelEn: "Bank account No. (if by transfer)", type: "text" },
    { key: "duration", label: "ხელშეკრულების ვადა", labelEn: "Contract term", type: "text", required: true },
  ],
  "employment-contract": [
    { key: "employer", label: "დამსაქმებელი", labelEn: "Employer", type: "text", required: true },
    { key: "employerId", label: "დამსაქმებლის საიდენტიფიკაციო/პირადი ნომერი", labelEn: "Employer's identification/personal number", type: "text", required: true },
    { key: "employerAddress", label: "დამსაქმებლის მისამართი", labelEn: "Employer's address", type: "text", required: true },
    { key: "employee", label: "თანამშრომელი", labelEn: "Employee", type: "text", required: true },
    { key: "employeeId", label: "თანამშრომლის პირადი ნომერი", labelEn: "Employee's personal number", type: "text", required: true },
    { key: "employeeAddress", label: "თანამშრომლის მისამართი", labelEn: "Employee's address", type: "text", required: true },
    { key: "position", label: "პოზიცია", labelEn: "Position", type: "text", required: true },
    { key: "salary", label: "ხელფასი", labelEn: "Salary", type: "text", required: true },
    { key: "salaryPaymentMethod", label: "ხელფასის გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", labelEn: "Salary payment method (cash/bank transfer)", type: "text", required: true },
    { key: "bankAccount", label: "თანამშრომლის საბანკო ანგარიშის № (თუ გადარიცხვაა)", labelEn: "Employee's bank account No. (if by transfer)", type: "text" },
    { key: "startDate", label: "დაწყების თარიღი", labelEn: "Start date", type: "date", required: true },
  ],
  "power-of-attorney": [
    { key: "principal", label: "მინდობელი", labelEn: "Principal", type: "text", required: true },
    { key: "idNumber", label: "მინდობელის პირადი ნომერი", labelEn: "Principal's personal number", type: "text", required: true },
    { key: "principalAddress", label: "მინდობელის მისამართი", labelEn: "Principal's address", type: "text", required: true },
    { key: "agent", label: "მინდობილი პირი", labelEn: "Agent (attorney-in-fact)", type: "text", required: true },
    { key: "agentId", label: "მინდობილი პირის პირადი ნომერი", labelEn: "Agent's personal number", type: "text", required: true },
    { key: "agentAddress", label: "მინდობილი პირის მისამართი", labelEn: "Agent's address", type: "text", required: true },
    { key: "scope", label: "მინდობის ფარგლები", labelEn: "Scope of authority", type: "textarea", required: true },
  ],
  "demand-letter": [
    { key: "yourName", label: "შენი სახელი და გვარი", labelEn: "Your full name", type: "text", required: true },
    { key: "yourAddress", label: "შენი მისამართი", labelEn: "Your address", type: "text", required: true },
    { key: "recipient", label: "ადრესატი", labelEn: "Recipient", type: "text", required: true },
    { key: "amount", label: "მოთხოვნილი თანხა", labelEn: "Amount claimed", type: "text" },
    { key: "paymentMethod", label: "გადახდის სასურველი მეთოდი (ნაღდი/საბანკო გადარიცხვა)", labelEn: "Preferred payment method (cash/bank transfer)", type: "text" },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვას ითხოვ)", labelEn: "Bank account No. (if requesting a transfer)", type: "text" },
    { key: "reason", label: "მოთხოვნის საფუძველი", labelEn: "Grounds for the demand", type: "textarea", required: true },
    { key: "deadline", label: "ვადა", labelEn: "Deadline", type: "text", required: true },
  ],
  "termination-notice": [
    { key: "employer", label: "დამსაქმებელი", labelEn: "Employer", type: "text", required: true },
    { key: "employee", label: "თანამშრომელი", labelEn: "Employee", type: "text", required: true },
    { key: "employeeId", label: "თანამშრომლის პირადი ნომერი", labelEn: "Employee's personal number", type: "text", required: true },
    { key: "employeeAddress", label: "თანამშრომლის მისამართი", labelEn: "Employee's address", type: "text", required: true },
    { key: "reason", label: "საფუძველი", labelEn: "Grounds", type: "text", required: true },
    { key: "lastDay", label: "ბოლო სამუშაო დღე", labelEn: "Last working day", type: "date", required: true },
    { key: "compensationAmount", label: "კომპენსაციის ოდენობა (კანონით გათვალისწინების შემთხვევაში)", labelEn: "Compensation amount (if provided by law)", type: "text" },
  ],
  "service-agreement": [
    { key: "executor", label: "შემსრულებელი (სახელი, გვარი / დასახელება)", labelEn: "Contractor (full name / entity name)", type: "text", required: true },
    { key: "executorId", label: "შემსრულებლის პირადი/საიდენტიფიკაციო № ", labelEn: "Contractor's personal/identification No.", type: "text", required: true },
    { key: "executorAddress", label: "შემსრულებლის მისამართი", labelEn: "Contractor's address", type: "text", required: true },
    { key: "executorPhone", label: "შემსრულებლის ტელეფონი", labelEn: "Contractor's phone number", type: "text" },
    { key: "client", label: "დამკვეთი (სახელი, გვარი / დასახელება)", labelEn: "Client (full name / entity name)", type: "text", required: true },
    { key: "clientId", label: "დამკვეთის პირადი/საიდენტიფიკაციო №", labelEn: "Client's personal/identification No.", type: "text", required: true },
    { key: "clientAddress", label: "დამკვეთის მისამართი", labelEn: "Client's address", type: "text", required: true },
    { key: "clientPhone", label: "დამკვეთის ტელეფონი", labelEn: "Client's phone number", type: "text" },
    { key: "serviceDescription", label: "მომსახურების აღწერა", labelEn: "Description of services", type: "textarea", required: true },
    { key: "deadline", label: "მომსახურების ვადა/ვადები", labelEn: "Service deadline(s)", type: "text", required: true },
    { key: "price", label: "საფასური", labelEn: "Fee", type: "text", required: true },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", labelEn: "Payment method (cash/bank transfer)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვაა)", labelEn: "Bank account No. (if by transfer)", type: "text" },
  ],
  "claim-letter": [
    { key: "senderName", label: "გამომგზავნის სახელი და გვარი", labelEn: "Sender's full name", type: "text", required: true },
    { key: "senderId", label: "გამომგზავნის პირადი ნომერი", labelEn: "Sender's personal number", type: "text" },
    { key: "senderAddress", label: "გამომგზავნის მისამართი", labelEn: "Sender's address", type: "text", required: true },
    { key: "senderPhone", label: "გამომგზავნის ტელეფონი", labelEn: "Sender's phone number", type: "text" },
    { key: "recipientName", label: "ადრესატი (ვის ეგზავნება პრეტენზია)", labelEn: "Recipient (who the claim is addressed to)", type: "text", required: true },
    { key: "recipientAddress", label: "ადრესატის მისამართი", labelEn: "Recipient's address", type: "text" },
    { key: "grounds", label: "პრეტენზიის ფაქტობრივი საფუძველი", labelEn: "Factual grounds for the claim", type: "textarea", required: true },
    { key: "demand", label: "კონკრეტული მოთხოვნა", labelEn: "Specific demand", type: "textarea", required: true },
    { key: "amount", label: "მოთხოვნილი თანხა (ასეთის არსებობისას)", labelEn: "Amount claimed (if any)", type: "text" },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", labelEn: "Payment method (cash/bank transfer)", type: "text" },
    { key: "bankAccount", label: "საბანკო ანგარიშის № (თუ გადარიცხვას ითხოვ)", labelEn: "Bank account No. (if requesting a transfer)", type: "text" },
    { key: "deadline", label: "პასუხის/შესრულების ვადა", labelEn: "Deadline for response/compliance", type: "text", required: true },
  ],
  "debt-claim": [
    { key: "creditorName", label: "კრედიტორის სახელი და გვარი", labelEn: "Creditor's full name", type: "text", required: true },
    { key: "creditorId", label: "კრედიტორის პირადი ნომერი", labelEn: "Creditor's personal number", type: "text" },
    { key: "creditorAddress", label: "კრედიტორის მისამართი", labelEn: "Creditor's address", type: "text", required: true },
    { key: "creditorPhone", label: "კრედიტორის ტელეფონი", labelEn: "Creditor's phone number", type: "text" },
    { key: "debtorName", label: "მოვალის სახელი და გვარი", labelEn: "Debtor's full name", type: "text", required: true },
    { key: "debtorAddress", label: "მოვალის მისამართი", labelEn: "Debtor's address", type: "text", required: true },
    { key: "debtBasis", label: "დავალიანების საფუძველი (სესხის ხელშეკრულება, ხელწერილი, თარიღი და სხვ.)", labelEn: "Basis of the debt (loan agreement, promissory note, date, etc.)", type: "textarea", required: true },
    { key: "principalAmount", label: "ძირითადი თანხა", labelEn: "Principal amount", type: "text", required: true },
    { key: "interestAmount", label: "დარიცხული პროცენტი/პირგასამტეხლო (ასეთის არსებობისას)", labelEn: "Accrued interest/penalty (if any)", type: "text" },
    { key: "totalAmount", label: "სულ გადასახდელი თანხა", labelEn: "Total amount due", type: "text", required: true },
    { key: "originalDueDate", label: "დაბრუნების თავდაპირველი ვადა", labelEn: "Original due date for repayment", type: "date" },
    { key: "newDeadline", label: "ახალი ვადა დაფარვისთვის", labelEn: "New deadline for repayment", type: "text", required: true },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", labelEn: "Payment method (cash/bank transfer)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის №", labelEn: "Bank account No.", type: "text" },
  ],
  "child-travel-consent": [
    { key: "parentName", label: "თანხმობის გამცემი მშობლის/კანონიერი წარმომადგენლის სახელი და გვარი", labelEn: "Full name of the consenting parent/legal guardian", type: "text", required: true },
    { key: "parentId", label: "მშობლის პირადი ნომერი", labelEn: "Parent's personal number", type: "text", required: true },
    { key: "parentAddress", label: "მშობლის მისამართი", labelEn: "Parent's address", type: "text", required: true },
    { key: "parentPhone", label: "მშობლის ტელეფონი", labelEn: "Parent's phone number", type: "text" },
    { key: "childName", label: "არასრულწლოვნის სახელი და გვარი", labelEn: "Minor's full name", type: "text", required: true },
    { key: "childDob", label: "არასრულწლოვნის დაბადების თარიღი", labelEn: "Minor's date of birth", type: "date", required: true },
    { key: "childDocument", label: "არასრულწლოვნის პირადობის/პასპორტის № ", labelEn: "Minor's ID/passport No.", type: "text", required: true },
    { key: "escort", label: "თანმხლები პირი (სახელი, გვარი, პ/ნ) ან „დამოუკიდებლად“", labelEn: "Accompanying person (full name, personal No.) or \"traveling alone\"", type: "text", required: true },
    { key: "destination", label: "დანიშნულების ქვეყანა/ქვეყნები", labelEn: "Destination country/countries", type: "text", required: true },
    { key: "travelPeriod", label: "მოგზაურობის პერიოდი", labelEn: "Travel period", type: "text", required: true },
    { key: "otherParentStatus", label: "მეორე მშობლის თანხმობის სტატუსი (თანხმობა ცალკე მოცემულია / მშობელი გარდაცვლილია ან მშობლის უფლება შეზღუდულია / ერთადერთი კანონიერი წარმომადგენელია და სხვ.)", labelEn: "Status of the other parent's consent (given separately / parent deceased or parental rights restricted / sole legal guardian, etc.)", type: "textarea", required: true },
  ],
  invoice: [
    { key: "invoiceNumber", label: "ინვოისის №", labelEn: "Invoice No.", type: "text", required: true },
    { key: "seller", label: "გამომწერი (გამყიდველი/მომსახურების მიმწოდებელი)", labelEn: "Issuer (seller/service provider)", type: "text", required: true },
    { key: "sellerId", label: "გამომწერის საიდენტიფიკაციო/პირადი №", labelEn: "Issuer's identification/personal No.", type: "text" },
    { key: "sellerAddress", label: "გამომწერის მისამართი", labelEn: "Issuer's address", type: "text" },
    { key: "buyer", label: "მიმღები (გადამხდელი)", labelEn: "Recipient (payer)", type: "text", required: true },
    { key: "buyerAddress", label: "მიმღების მისამართი", labelEn: "Recipient's address", type: "text" },
    { key: "items", label: "საქონელი/მომსახურება", labelEn: "Goods/services", type: "textarea", required: true },
    { key: "totalAmount", label: "სულ გადასახდელი თანხა", labelEn: "Total amount due", type: "text", required: true },
    { key: "dueDate", label: "გადახდის ვადა", labelEn: "Payment due date", type: "date", required: true },
    { key: "paymentMethod", label: "გადახდის მეთოდი (ნაღდი/საბანკო გადარიცხვა)", labelEn: "Payment method (cash/bank transfer)", type: "text", required: true },
    { key: "bankAccount", label: "საბანკო ანგარიშის №", labelEn: "Bank account No.", type: "text" },
  ],
  "acceptance-act": [
    { key: "actNumber", label: "აქტის №", labelEn: "Act No.", type: "text" },
    { key: "provider", label: "მიმცემი მხარე (შემსრულებელი/მიმწოდებელი)", labelEn: "Transferring party (contractor/supplier)", type: "text", required: true },
    { key: "providerId", label: "მიმცემის საიდენტიფიკაციო/პირადი №", labelEn: "Transferring party's identification/personal No.", type: "text" },
    { key: "providerAddress", label: "მიმცემის მისამართი", labelEn: "Transferring party's address", type: "text" },
    { key: "receiver", label: "მიმღები მხარე (დამკვეთი)", labelEn: "Receiving party (client)", type: "text", required: true },
    { key: "receiverId", label: "მიმღების საიდენტიფიკაციო/პირადი №", labelEn: "Receiving party's identification/personal No.", type: "text" },
    { key: "receiverAddress", label: "მიმღების მისამართი", labelEn: "Receiving party's address", type: "text" },
    { key: "contractRef", label: "საბაზისო ხელშეკრულების რეკვიზიტები (№, თარიღი)", labelEn: "Underlying contract details (No., date)", type: "text" },
    { key: "subjectDescription", label: "ჩაბარებული საქონლის/სამუშაოს/მომსახურების აღწერა", labelEn: "Description of goods/work/services delivered", type: "textarea", required: true },
    { key: "amount", label: "ღირებულება", labelEn: "Value", type: "text" },
    { key: "objections", label: "მხარეთა შენიშვნები/პრეტენზიები (ასეთის არარსებობისას — „არ არსებობს“)", labelEn: "Parties' remarks/objections (enter \"none\" if there are none)", type: "textarea", required: true },
  ],
};

export function fieldLabel(f: QuestionField, locale: Locale): string {
  return locale === "en" ? f.labelEn : f.label;
}
